{{-- resources/views/partials/header/_nav.blade.php --}}

@php
    /**
     * Header navigation partial.
     *
     * Expected variables:
     * - $header_bg (string) Optional. Used as background for off-canvas container.
     *
     * Notes:
     * - Avoid WP escaping helpers in Blade. Use ThemeContext ($theme) instead.
     * - $theme is shared globally by ViewServiceProvider.
     */
    $header_bg = $header_bg ?? '#313b45';

    /**
     * Prefer config-driven app name (Laravel style), fallback to WP blog name.
     */
    $siteName = (string) ( ( $config['app.name'] ?? $config['app']['name'] ?? '' ) ?: '' );
    if ( $siteName === '' && function_exists( 'get_bloginfo' ) ) {
        $siteName = (string) get_bloginfo( 'name' );
    }
@endphp

<!-- Off–canvas menu / mobile + desktop menu wrapper -->
<div
        class="yivic-lite-header__links nav-links"
        id="yivicMobileMenu"
        style="background: {{ $theme->attr( $header_bg ) }};"
>
    <div class="yivic-lite-header__sidebar-logo sidebar-logo">
        <span class="yivic-lite-header__logo-name logo-name">
            {{ $theme->e( $siteName ) }}
        </span>

        <button
                class="yivic-lite-header__close yivicCancel-icon"
                id="yivicMenuClose"
                type="button"
                aria-label="{{ $theme->attr( $theme->__( 'Close menu' ) ) }}"
        >
            <img
                    class="yivic-lite-header__close-icon"
                    src="{{ $theme->url( $theme->asset( 'public-assets/dist/img/yivic-lite-cancel-icon.svg' ) ) }}"
                    alt="{{ $theme->attr( $theme->__( 'Close menu' ) ) }}"
            >
        </button>
    </div>

    @php
        /**
         * wp_nav_menu() is a WordPress API and returns HTML.
         * We keep this in PHP and output as raw HTML below.
         *
         * Security note:
         * - Menu output is generated by WP and is generally safe to output.
         * - If you ever allow untrusted HTML inside menu items, add a sanitization layer.
         */
        $menuHtml = wp_nav_menu([
            'theme_location'  => 'yivic-lite-primary',
            'container'       => 'div',
            'container_class' => 'yivic-lite-header__menu-container menu-categories-container',
            'menu_class'      => 'yivic-lite-header__menu links main-nav dropdown-menu sf-menu',
            'menu_id'         => 'yivic-lite-primary-menu',
            'fallback_cb'     => 'yivic_menu_fallback',
            'depth'           => 0,
            'echo'            => false,
        ]);
    @endphp

    {!! $menuHtml !!}
</div>
